clientbase/urls.py
from django.contrib import admin
from django.urls import re_path, include
from . import views

urlpatterns = [
    re_path(r'^admin/', admin.site.urls),
    
    re_path(r'^$', views.loginView.as_view(), name='login'),
    re_path(r'^logout$',  views.logout_view, name='logout'),
    re_path(r'^dashboard/$', views.Dashboard, name='dashboard'),

    re_path(r'^profile/$', views.ProfileView, name='profile'),
    re_path(r'^profile/agency/edit/(?P<pk>[a-zA-Z0-9_.-]+)', views.UpdateAgency.as_view(), name='editAgency'),
    re_path(r'^profile/agency/(?P<pk>[a-zA-Z0-9_.-]+)', views.AgencyDetail.as_view(), name='getAgency'),
    re_path(r'^profile/agency/$', views.CreateAgency.as_view(), name='agency'),
    
    re_path(r'^tasks/', include("tasks.urls")),
    re_path(r'^dir/', include("directory.urls")),
    re_path(r'^calendar/', include("planner.urls")),

]

directory/urls.py
from django.urls import re_path, include
from . import views


app_name='directory'

urlpatterns = [
	re_path(r'^update_doc/(?P<docId>[a-zA-Z0-9_.-]+)', views.docUpdateView.as_view(), name='eventUpdate'),
	re_path(r'^delete_doc/(?P<docId>[a-zA-Z0-9_.-]+)', views.docDeleteView.as_view(), name='eventDelete'),
    re_path(r'^(?P<pk>[a-zA-Z0-9_.-]+)/upload', views.UploadDocument.as_view(), name='eventCreate'),

 	re_path(r'^new', views.CreatePatientView.as_view(), name='create'),
 	re_path(r'^edit/(?P<pk>[a-zA-Z0-9_.-]+)', views.UpdatePatientView.as_view(), name='update'),
 	re_path(r'^(?P<pk>[a-zA-Z0-9_.-]+)', views.DetailPatientView.as_view(), name='retrieve'),
 	re_path(r'^$', views.IndexPatientView.as_view(), name='list'), 
]

planner/urls.py
from django.urls import re_path
from . import views

app_name='calendar'
urlpatterns = [
	re_path(r'^get$', views.getEvents), 
	re_path(r'^pull$', views.pullEvent),
	re_path(r'^post$', views.addEvents), 
	re_path(r'^update$', views.updateEvents),
	re_path(r'^delete$', views.deleteEvent),  
	re_path(r'^$', views.CalendarView, name='schedule'),
]

tasks/urls.py
from django.urls import re_path
from . import views

app_name='task'
urlpatterns = [
	re_path(r'^pull$', views.getTable),
	re_path(r'^$', views.taskView, name='upcoming'),
]

clientbase/forms.py
from django.contrib.auth.models import User
from django import forms

class UserForm(forms.ModelForm):
	password=forms.CharField(widget=forms.PasswordInput())
	class Meta:
		model = User
		fields = ['username', 'password']

clientbase/views.py
from tasks import views
from .forms import UserForm
from django.views import generic
from django.views.generic import View
from django.urls import reverse
from django.shortcuts import render, redirect
from django.http import HttpResponseRedirect, Http404
from directory.models import Patient, Agency, Document
from django.contrib.auth import authenticate, login, logout
from django.views.generic.edit import CreateView, UpdateView, DeleteView
# this is for login request
from django.contrib.auth.decorators import login_required
from django.utils.decorators import method_decorator
from .class_decorator import class_view_decorator


# Create your views here.
@login_required
def Dashboard(request):
	patA = request.user.patient_set.filter(status__iexact='active').count()
	patI = request.user.patient_set.filter(status__iexact='inactive').count()
	events = Document.objects.filter(patient__agency__desNurse=request.user.id).filter(file='').count()
	tasks = len(views.getContext(request.user, 'weekly'))
	context={
            "patNumA"	: patA,
            "patNumI"	: patI,
            "taskNum"	: tasks,
            "events"	: events,
            }
	return render(request, 'dashboard.html', context)



@login_required
def ProfileView(request):
	return render(request, 'directory/profile.html')



@class_view_decorator(login_required)
class CreateAgency(CreateView):
	model = Agency
	fields = ['companyName', 'phoneNumber', 'faxNumber', 'companyEmail', 
				'desNurse', 'placeID', 'formatted_address', 'ext_address']

	def get_form(self, form_class=None):
		# instantiate using parent
		form = super(CreateAgency, self).get_form(form_class) 
		return addStyleAgencyForm(form)


	def form_valid(self, form):
		candidate = form.save(commit=False)
		candidate.desNurse= self.request.user 
		candidate.save()
		return HttpResponseRedirect(reverse('profile'))



@class_view_decorator(login_required)
class UpdateAgency(UpdateView):
	model = Agency
	fields = ['companyName', 'phoneNumber', 'faxNumber', 'companyEmail',
				'placeID', 'formatted_address', 'ext_address']

	# this is to make sure: one user cant access other user's objects
	def get_queryset(self):
		queryset = super(UpdateAgency, self).get_queryset()
		return queryset.filter(desNurse=self.request.user.id)

	def get_form(self, form_class=None):
		# instantiate using parent
		form = super(UpdateAgency, self).get_form(form_class) 
		return addStyleAgencyForm(form)


def addStyleAgencyForm(form):
	# add HTML attributes to form fields
	for field in form.fields:
		form.fields[field].widget.attrs.update({'class': 'form-control'})

	form.fields["companyName"].widget.attrs.update({'placeholder':'Agency Name'})
	form.fields["companyEmail"].widget.attrs.update({'placeholder':'Agency Email'})
	form.fields["phoneNumber"].widget.attrs.update({'placeholder':'Phone Number'})
	form.fields["faxNumber"].widget.attrs.update({'placeholder':'Fax Number'})
	form.fields["formatted_address"].widget.attrs.update({'placeholder':'Enter your address','id': 'autocomplete'})
	form.fields["ext_address"].widget.attrs.update({'placeholder':'Apt/Suite'})
	return form

@class_view_decorator(login_required)
class AgencyDetail(generic.DetailView):
	model = Agency
	template_name="directory/agencyDetail.html"

	# this is to make sure: one user cant access other user's objects
	def get_queryset(self):
		queryset = super(AgencyDetail, self).get_queryset()
		return queryset.filter(desNurse=self.request.user.id)


class loginView(View):
	form_class = UserForm
	template_name="ClientBase.html"
	
	def get(self, request):
		if request.user.is_authenticated:
			return redirect('dashboard')
		else: 
			form=self.form_class(None)
			form.fields["username"].widget.attrs.update({'placeholder':'Hint: guest'})
			form.fields["password"].widget.attrs.update({'placeholder':'Hint: demoview'})
			return render(request, self.template_name, {'form': form})

	# process the registeration data
	def post(self, request):
		# logs in the user
		user=authenticate(username=request.POST['username'], password=request.POST['password'])
		if user is not None:
			if user.is_active:
				login(request, user)
				# try to see if the user wanted to go somewhere before the log in
				if request.GET.get('next') != None:
					return HttpResponseRedirect(request.GET.get('next'))
				else:
					return redirect('dashboard')
		return redirect('login')



def logout_view(request):
    logout(request)
    return redirect('login')

templates/ClientBase.html
<!DOCTYPE html>


{% load static %}

<html>
  <head>
    <title>ClientBase.space</title>

    <link href="https://fonts.googleapis.com/css?family=Open+Sans:300,400,600,700|Quicksand" rel="stylesheet">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
    <link rel="stylesheet" type="text/css" href="../static/css/styleHP.css">

  </head>

  <body>  
    <div class="header" > 
        <div id="header-text">
        <h1>Manage Patients Effortlessly</h1>
        <h2>Paperless, reliable, and effective way to manage clients.</h2>
        <button id ="btn" onclick="document.getElementById('id01').style.display='block'" style="width: 20%;">Login</button>
        </div>
    </div>

    <div id="id01" class="modal">
      <div class="modal-content animate">
        <form method='post' role='form' >
          {% csrf_token %}
          <div class="imgcontainer">
            <span onclick="document.getElementById('id01').style.display='none'" class="close" title="Close Modal">&times;</span>
            <img src="/static/PageIcons/1497137238_female1.png" alt="Avatar" class="avatar">
          </div>

          <div class="container">
            <label><b>Username</b></label>
            {{form.username}} 

            <label><b>Password</b></label>
            {{form.password}}
              
            <button type="submit">Login</button>
          </div>
        </form>
        <div class="container" style="background-color:#f1f1f1">
          <button onclick="document.getElementById('id01').style.display='none'" class="cancelbtn">Cancel</button>
          <span class="psw"><a href="#" title="User Alert" data-toggle="popover" data-trigger="focus" data-content="Contact: eldorbek0526@gmail.com"> Forgot password?</a></span>
        </div>
      </div>
    </div>
    <div class="footer" >
      <h4 id="dev"> Developed by Eldor Bekpulatov</h4>
    </div>


    <script>
      // Get the modal
      var modal = document.getElementById('id01');

      // When the user clicks anywhere outside of the modal, close it
      window.onclick = function(event) {
          if (event.target == modal) {
              modal.style.display = "none"; } };
      
      $(document).ready(function(){
          $('[data-toggle="popover"]').popover();   
      });
    </script>

  </body>
</html>

templates/index.html
<!DOCTYPE html>

{% load static %}

<html lang="en">

<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>ClientBase.Space</title>

    <!-- Custom CSS -->
    <link href="https://cdnjs.cloudflare.com/ajax/libs/startbootstrap-sb-admin-2/3.3.7+1/css/sb-admin-2.css" rel="stylesheet">
    <!-- Custom Fonts -->
    <link href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet" type="text/css">

    <!-- Morris Charts JavaScript & StyleSheet-->
    <script src="https://code.jquery.com/jquery-1.8.2.min.js"></script> <!--DO NOT MOVE --> 
     <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script> <!--DO NOT MOVE --> 
    <script src="https://cdnjs.cloudflare.com/ajax/libs/morris.js/0.5.1/morris.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/raphael/2.1.0/raphael-min.js"></script>
    <link href="//cdnjs.cloudflare.com/ajax/libs/morris.js/0.5.1/morris.css" rel="stylesheet">

    <!-- Bootstrap Core JavaScript -->
    <script src='https://cdnjs.cloudflare.com/ajax/libs/moment.js/2.20.1/moment.min.js'></script> <!--DO NOT MOVE -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>

    <!-- Include DateTimePicker -->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-datetimepicker/4.17.47/css/bootstrap-datetimepicker.min.css" />
    <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-datetimepicker/4.17.47/js/bootstrap-datetimepicker.min.js"></script>
    
    <!--Include Data Tables-->
    <script src="https://cdn.datatables.net/1.10.15/js/jquery.dataTables.min.js"></script>
    <script src="https://cdn.datatables.net/1.10.12/js/dataTables.bootstrap.min.js"></script>
    <!--Extra style for the dataTables -->
    <style type="text/css">
        .pagination{margin: 2px 0px;} 
        #myTable_length  {float: left;}
        #myTable_filter {float: right;} 
        #myTable_paginate {float: right;} 
    </style>

    <!-- Metis Menu Plugin JavaScript -->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/metisMenu/2.7.0/metisMenu.js"></script>

    <!-- Custom Theme JavaScript -->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/startbootstrap-sb-admin-2/3.3.7+1/js/sb-admin-2.js"></script>

    <!-- Include DateRange Picker -->
    <script type="text/javascript" src="https://cdn.jsdelivr.net/bootstrap.daterangepicker/2/daterangepicker.js"></script>
    <link rel="stylesheet" type="text/css" href="https://cdn.jsdelivr.net/bootstrap.daterangepicker/2/daterangepicker.css" />

</head>

<body>
    <div id="wrapper" >
        <!-- Navigation -->
        <nav class="navbar navbar-default navbar-static-top" role="navigation" style="margin-bottom: 0;">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a class="navbar-brand" href="{% url 'dashboard' %}" style="margin-left: 20px;">ClientBase.space</a>
            </div>
          
            <div class="navbar-default sidebar" role="navigation">
                <div class="sidebar-nav navbar-collapse">
                    <ul class="nav" id="side-menu">
                        <li>
                            <img src="../static/PageIcons/1497137238_female1.png" class="img-rounded center-block" width="125" height="125" style="margin-top: 10px">
                            <p class="text-center" style="margin-top: 5px;">{{ request.user.get_full_name }}<br></p>
                        </li>
                        <li>
                            <a href="{% url 'dashboard' %}"><i class="fa fa-dashboard fa-fw"></i> Dashboard</a>
                        </li>
                        <li>
                            <a href="#"><i class="fa fa-list-alt fa-fw"></i> Directory<span class="fa arrow"></span></a>
                            <ul class="nav nav-second-level">
                                <li>
                                    <a href="{% url 'directory:list' %}"> View All</a>
                                </li>
                                <li>
                                    <a href="{% url 'directory:create' %}"> Add New</a>
                                </li>
                            </ul>
                            <!-- /.nav-second-level -->
                        </li>

                        <li>
                            <a href="{% url 'task:upcoming' %}"><i class="fa fa-tasks fa-fw"></i> Tasks</a>
                        </li>
                        
                        <li>
                            <a href="{% url 'calendar:schedule' %}"><i class="fa fa-calendar fa-fw"></i> Calendar</a>
                        </li>

                        <li>
                            <a href="#"><i class="fa fa-user-md fa-fw"></i> User<span class="fa arrow"></span></a>
                            <ul class="nav nav-second-level">
                                <li>
                                    <a href="{% url 'profile' %}">Profile</a>
                                </li>
                                <li>
                                    <a href="{% url 'logout' %}">Log Out</a>
                                </li>
                            </ul>
                            <!-- /.nav-second-level -->
                        </li>
                    </ul>
                </div>
                <!-- /.sidebar-collapse -->
            </div>
            <!-- /.navbar-static-side -->
        </nav>

        {% block content %}

        {% endblock content %}

    </div>
    <!-- /#wrapper -->
    
    <nav class="navbar fixed-bottom navbar-light bg-faded navbar-default" style="margin: 0px;">
        <a class="navbar-brand" href="/dashboard">ClientBase.Space</a>
    </nav>

</body>

</html>

templates/member.html
<!DOCTYPE html>

{% load static from staticfiles %}

<html lang="en">

<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>ClientBase.Space</title>

    <!-- Custom CSS -->
    <link href="https://cdnjs.cloudflare.com/ajax/libs/startbootstrap-sb-admin-2/3.3.7+1/css/sb-admin-2.css" rel="stylesheet">
    <!-- Custom Fonts -->
    <link href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet" type="text/css">

    <!-- Morris Charts JavaScript & StyleSheet-->
    <script src="https://code.jquery.com/jquery-1.8.2.min.js"></script> <!--DO NOT MOVE --> 
     <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script> <!--DO NOT MOVE --> 
    <script src="https://cdnjs.cloudflare.com/ajax/libs/morris.js/0.5.1/morris.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/raphael/2.1.0/raphael-min.js"></script>
    <link href="//cdnjs.cloudflare.com/ajax/libs/morris.js/0.5.1/morris.css" rel="stylesheet">

    <!-- Bootstrap Core JavaScript -->
    <script src='https://cdnjs.cloudflare.com/ajax/libs/moment.js/2.20.1/moment.min.js'></script> <!--DO NOT MOVE -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>

    <!-- Include DateTimePicker -->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-datetimepicker/4.17.47/css/bootstrap-datetimepicker.min.css" />
    <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-datetimepicker/4.17.47/js/bootstrap-datetimepicker.min.js"></script>
    
    <!--Include Data Tables-->
    <script src="https://cdn.datatables.net/1.10.15/js/jquery.dataTables.min.js"></script>
    <script src="https://cdn.datatables.net/1.10.12/js/dataTables.bootstrap.min.js"></script>
    <!--Extra style for the dataTables -->
    <style type="text/css">
        .pagination{margin: 2px 0px;} 
        #myTable_length  {float: left;}
        #myTable_filter {float: right;} 
        #myTable_paginate {float: right;} 
    </style>

    <!-- Metis Menu Plugin JavaScript -->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/metisMenu/2.7.0/metisMenu.js"></script>

    <!-- Custom Theme JavaScript -->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/startbootstrap-sb-admin-2/3.3.7+1/js/sb-admin-2.js"></script>

    <!-- Include DateRange Picker -->
    <script type="text/javascript" src="https://cdn.jsdelivr.net/bootstrap.daterangepicker/2/daterangepicker.js"></script>
    <link rel="stylesheet" type="text/css" href="https://cdn.jsdelivr.net/bootstrap.daterangepicker/2/daterangepicker.css" />

</head>

<body>
    <div id="wrapper" >
        <!-- Navigation -->
        <nav class="navbar navbar-default navbar-static-top" role="navigation" style="margin-bottom: 0;">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a class="navbar-brand" href="{% url 'dashboard' %}" style="margin-left: 20px;">ClientBase.space</a>
            </div>
          
            <div class="navbar-default sidebar" role="navigation">
                <div class="sidebar-nav navbar-collapse">
                    <ul class="nav" id="side-menu">
                        <li>
                            <img src="{% static 'PageIcons/1497137238_female1.png' %}" class="img-rounded center-block" width="125" height="125" style="margin-top: 10px">
                            <p class="text-center" style="margin-top: 5px;">{{ request.user.get_full_name }}<br></p>
                        </li>
                        <li>
                            <a href="{% url 'dashboard' %}"><i class="fa fa-dashboard fa-fw"></i> Dashboard</a>
                        </li>
                        <li>
                            <a href="#"><i class="fa fa-list-alt fa-fw"></i> Directory<span class="fa arrow"></span></a>
                            <ul class="nav nav-second-level">
                                <li>
                                    <a href="{% url 'directory:list' %}"> View All</a>
                                </li>
                                <li>
                                    <a href="{% url 'directory:create' %}"> Add New</a>
                                </li>
                            </ul>
                            <!-- /.nav-second-level -->
                        </li>

                        <li>
                            <a href="{% url 'task:upcoming' %}"><i class="fa fa-tasks fa-fw"></i> Tasks</a>
                        </li>
                        
                        <li>
                            <a href="{% url 'calendar:schedule' %}"><i class="fa fa-calendar fa-fw"></i> Calendar</a>
                        </li>

                        <li>
                            <a href="#"><i class="fa fa-user-md fa-fw"></i> User<span class="fa arrow"></span></a>
                            <ul class="nav nav-second-level">
                                <li>
                                    <a href="{% url 'profile' %}">Profile</a>
                                </li>
                                <li>
                                    <a href="{% url 'logout' %}">Log Out</a>
                                </li>
                            </ul>
                            <!-- /.nav-second-level -->
                        </li>
                    </ul>
                </div>
                <!-- /.sidebar-collapse -->
            </div>
            <!-- /.navbar-static-side -->
        </nav>

        {% block content %}

        {% endblock content %}

    </div>
    <!-- /#wrapper -->
    
    <nav class="navbar fixed-bottom navbar-light bg-faded navbar-default" style="margin: 0px;">
        <a class="navbar-brand" href="/dashboard">ClientBase.Space</a>
    </nav>

</body>

</html>